### ISSUE TITLE
Circa le lezioni su Zoom

### ISSUE THREAD

**Issue by AlessandroDiGioacchino** [f14-bertolotti/SAD-unimi#1]
Buongiorno.
Le lezioni saranno disponibili anche in differita per conformarsi alla parte di teoria, oppure il laboratorio si svolgerà esclusivamente in diretta?

**Comment by f14-bertolotti** [comment]
Ciao.
In realtà non pianifico di registrare le lezioni.
Comunque dopo ogni lab cercherò di mettere a disposizione dei notebook
riassuntivi con le domande che sono saltate fuori e le note.
In questo modo, potete comunque rifarvi al notebook se non potete
partecipare.
L'unico vantaggio di partecipare dovrebbe essere quello di poter fare delle
domande "live".
Comunque, sono disponibile anche per rispondere alle vostre domande tramite
mail.


Il giorno gio 2 apr 2020 alle ore 15:09 DigiOhhh <notifications@github.com>
ha scritto:

**Comment by AlessandroDiGioacchino** [comment]
Va bene, grazie mille.
